### ISSUE TITLE
주식 기본 정보 데이타

### ISSUE THREAD

**Issue by isuphy** [mrchypark/tqk#1]
안녕하세요.

덕분에 한국주식 데이타를 잘 이용하고 있습니다.

혹시 주식 기본 정보 데이타를 get 할 수 있는 기능은 없는 건가요?
만약에 아직 가능하지 않다면, 그것은 데이타 소스의 문제 일까요, 아니면 해당 메쏘드가 없기 때문일까요?

고맙습니다.

isuphy

**Comment by mrchypark** [comment]
@isuphy  안녕하세요, 주식 기본 정보가 어떤 것인가요? 어디서 구할 수 있는지 알려주시면 반영해보겠습니다. 감사합니다.

**Comment by isuphy** [comment]
제가 한국 주식 용어에 익숙하지 않아서 다른 이름이 있을 수도 있겠네요.
키움 API에서는 그렇게 부르고 있어서 그 이름을 사용했습니다.
"종목코드",
            "종목명",            "결산월",            "액면가",            "자본금",            "상장주식",
            "신용비율",            "연중최고",            "연중최저",            "시가총액",
            "시가총액비중",            "외인소진률",            "대용가",            "PER",
            "EPS",            "ROE",            "PBR",            "EV",            "BPS",            "매출액",
            "영업이익",            "당기순이익",            "250최고",            "250최저",            "시가",
            "고가",            "저가",            "상한가",            "하한가",            "기준가",            "예상체결가",
            "예상체결수량",            "250최고가일",            "250최고가대비율",            "250최저가일",
            "250최저가대비율",            "현재가",            "대비기호",            "저일대비",            "등락율",
            "거래량",            "거래대비",            "액면가단위"

정보들을 말씀드린 것 이었습니다. 저도 찾아보고 먼저 찾게되면 이 곳에 정보를 공유하도록 하겠습니다.
Paxnet html query 에 method로 존재할 것 같은데, method리스트를 알 수 있는 방법이 없네요.

고맙습니다.

isuphy

**Comment by mrchypark** [comment]
@isuphy 아 제가 주식을 잘 모릅니다.ㅠ_ㅠ 웹 페이지에라도 보이는 곳이 있으면 알려주세요. 한번 확인해 보겠습니다. 감사합니다.

**Comment by isuphy** [comment]
http://paxnet.moneta.co.kr/stock/analysis/presentValue?abbrSymbol=005930
에서 중간에 '현재가'를 클릭하시면 '기본 주가정보' 라는게 뜹니다.
전에 작업하신 sejongFinData 의 재무 정보랑 같지는 않지만 비슷한 거라고 생각합니다.
paxnet 웹페이지에 뜨는 것을 보면 쿼리 명령어가 있을 것 같습니다만, 확실하지는 않습니다.

고맙습니다.

isuphy

**Comment by mrchypark** [comment]
@isuphy 오 그렇군요 가져올 수 있는지 알아보고 반영하면서 이슈 닫겠습니다. 감사합니다.

**Comment by mrchypark** [comment]
https://github.com/mrchypark/tqk/issues/32

여기서 처리함
