### ISSUE TITLE
우선주?

### ISSUE THREAD

**Issue by Sumeun** [mrchypark/tqk#18]
안녕하세요? 좋은 패키지 공개해주셔서 감사합니다.

  한 번 써보고 있는데, "우선주"는 자료를 못 읽어오는 것 같아서요.

  예를 들면 LG화학과 LG화학우가 따로 있습니다.

  https://finance.daum.net/domestic/search?q=LG%ED%99%94%ED%95%99

  방법이 있을까요?

**Comment by mrchypark** [comment]
안녕하세요, 

둘다 코스피에 포함되어 있어서 동작하는 것을 확인했습니다.
종목명으로 작성하는 건 아직 기능 개선이 필요해 보이구요 ㅜㅠ

종목 코드로 가능합니다.

``` r
tqk_get("051915")
tqk_get("A051915")
tqk_get("051910")
tqk_get("A051910")
```
