### ISSUE TITLE
누구나 할수있지만 연습삼아 종가 기준 수익 함수를 만들었어요.

### ISSUE THREAD

**Issue by seohyunjun** [mrchypark/tqk#19]
```
 asset<- function(x,y,z){ 
    x <- enc2utf8(x)
    x <- code[grep("x",code$name),1]
    x<- tqk_get(x,from=Sys.Date()-1)
    x <- x[,5]
    v <- (x-y)*z
    print(v)
x=종목이름 
y=매수 단가
z=수량
asset("종목이름",매수 단가,수량)
```
깃허브 적용법을 몰라 처음에 웹에서 주식 정보를 가져오다가 처음 알게되서 적용해보았습니다.

감사합니다.

**Comment by mrchypark** [comment]
@seohyunjun 안녕하세요! 좋은 코드 공유해주셔서 감사합니다. 공유해주신 것과 별개로 tqk는 데이터 제공을 더 집중하면 어떨까 생각하고 있습니다. 그래도 혹시 괜찮으시다면 이슈를 유지하고 있으면 다른 분들도 보고 영감을 받을 수 있지 않을까 싶습니다. 감사합니다.

**Comment by seohyunjun** [comment]
r 연습중이라 더 연습해서 도움이 되도록 노력하겠습니다. 패키지 감사합니다.
