### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chulhongsung** [mrchypark/tqk#20]
안녕하세요, tqk를 이용해서 주식데이터를 불러오려고 합니다.

code <- code_get()
code %>% filter(name == '대우건설')
실행시 다음과 같은 에러가 발생합니다.

Error in data.matrix(data) : invalid multibyte string at '<eb><82><98>?몃찓<eb>뵓<ec>뒪'

혹시 해결 방법 아시나요?

**Comment by seohyunjun** [comment]
한글 인코딩하는 enc2utf8()로 변환후 검색해보세요~

**Comment by chulhongsung** [comment]
혹시 다음과 같이하는 것이 맞나요? 똑같은 에러가 발생하네요.

code <- code_get()

code$name <- enc2utf8(code$name)

code %>% filter(name == '대우건설')

**Comment by seohyunjun** [comment]
#install.packages("devtools")
#install.packages("rmarkdown")
#install.packages("knitr")
library(knitr)
library(devtools)
library(rmarkdown)
#devtools::install_github("mrchypark/tqk")
library(tqk)
library(utf8)
code <- code_get()
#code

p=Sys.Date()-t

#코드 알아 내기ex)sscode <- code[grep("^삼성전자$", code$name),1]
daewooship_code <- code[grep("^대우조선해양$",code$name),1]
#daewooship_code
#help("tqk_get")
#코드 적용
k=Sys.Date()-1

daewooship <- tqk_get(daewooship_code,from=p)
daewooship
plot(daewooship$date,daewooship$low)
#daewooship
daewoo_close_v <- daewooship[,5]
my_d <- (daewoo_close_v-29200)*10
#my_d

#맥쿼리 인프라  
mac_code <- code[grep("^맥쿼리인프라$",code$name),1]
#mac_code

mac <- tqk_get(mac_code,from=p)
#mac
mac_close_v <- mac[,5]
my_m <- (mac_close_v-10750)*19

#help("tqk_get")
t=Sys.Date()-as.Date('2019-05-28')
t=as.numeric(t)
t
p=Sys.Date()-t
#my_m
my_asset <- my_d+my_m

#my_asset
rownames(my_asset) <- Sys.Date()-nrow(my_asset)+1:nrow(my_asset)
plot(Sys.Date()-nrow(my_asset)+1:nrow(my_asset),my_asset$close,xlab = "종가 기준 수익")



asset <- NA
asset <- c(asset,my_asset)
asset

colnames(my_asset) <- Sys.Date() 
my_asset
plot(asset)
x <- "대우조선해양"
enc2utf8(x)
asset<- function(x,y,z){
    x <- enc2utf8(x)
    x <- code[grep(x,code$name),1]
    x<- tqk_get(x,from=Sys.Date()-1)
    x <- x[,5]
    v <- (x-y)*z
    print(v)
}
asset("맥쿼리인프라",0,1)

setwd("C:/Users/Lenovo/Desktop")
#pdf 저장 cairo_pdf()
pdf("pdf1.pdf")
plot(Sys.Date()-nrow(my_asset)+1:nrow(my_asset),my_asset$close,xlab = "종가 기준 수익",type="l")

plot1 <-plot(Sys.Date()-nrow(my_asset)+1:nrow(my_asset),my_asset$close,xlab = "종가 기준 수익",type="l")

참고해주세요 ~

**Comment by chulhongsung** [comment]
확인 결과 패키지 충돌이었네요. dplyr::filter()로 하니 해결되었습니다. 감사합니다.

**Comment by mrchypark** [comment]
좋은 이슈 쓰레드를 만들어주셔서 두분 대단히 감사드립니다.

**Comment by mrchypark** [comment]
@all-contributors please add @chulhongsung for question
@all-contributors please add @seohyunjun  for question

**Comment by mrchypark** [comment]
@all-contributors please add @chulhongsung for question

**Comment by mrchypark** [comment]
@all-contributors please add @seohyunjun for question

**Comment by mrchypark** [comment]
@all-contributors please add @seohyunjun for question

**Comment by mrchypark** [comment]
@all-contributors please add @seohyunjun for question
