### ISSUE TITLE
네이버 증권에 있는 재무제표 크롤링 하는 법

### ISSUE THREAD

**Issue by dragongalee** [mrchypark/tqk#25]
안녕하세요 박사님
명지대에서 특강 감사히 잘 들었습니다!

다름이 아니라 제가 필요한 30개 종목의 제무제표를 원하는 항목만 크롤링을 하려고 하는데 그 방법이 궁금해 질문 남깁니다!!

5개년치가 한 번에 나오는 네이버 금융에서 크롤링하려고 합니다.

https://finance.naver.com/item/coinfo.nhn?code=005930

다만 위 사이트로 들어가면 기업현황이 첫 페이지로 나와서 재무분석을  눌러주어야 합니다.

![fin_naver_0](https://user-images.githubusercontent.com/33924348/69850597-f44f1400-12c2-11ea-8e11-890eab37dadd.JPG)

 감사합니다!

**Comment by mrchypark** [comment]
출처가 fnguide 이고 저작권으로 소송을 할 여지가 있는 고지를 해놨네요. 물론 제가 직접 데이터베이스화 하는 것이 아니고, 데이터베이스화 하는 도구를 제공하는 것이긴 합니다만 말이죠.

혹시 다른 소스가 있을까요?

![image](https://user-images.githubusercontent.com/6179259/70391257-70113500-1a16-11ea-8d4c-a342d04196bf.png)
