### ISSUE TITLE
code_get()을 하면 KOSPI 자료만 달려옵니다. 

### ISSUE THREAD

**Issue by gbkim01** [mrchypark/tqk#26]
안녕하세요. 
코드 개요란에 설명된 내용과 좀 다른 부분이 있어서 글을 남깁니다. 

1. 코드 개요란에 `code_get()`을 하면 "code", "name", "category"의 항목에 대한 정보를 내려받는다고 나오는데 제가 하면 "code", "name", "market"의 정보를 다운받습니다. 

2. 코드 개요에는 `code_get()`을 하면 코스피, 코스닥, ETF 등 모든 카테고리에 대한 정보를 내려받는 것으로 나오는데 제가 하면 코스피 정보만 나옵니다. 
  - 코스닥 정보를 가져오려면 `code_get(market="KOSDAQ")`이라고 해야 하고 `code_get(market="ALL")`일 겨우에는 KONEX, KOSDAQ, KOPI 정보만 가져옵니다.

**Comment by mrchypark** [comment]
@gbkim01 안녕하세요, 패키지에 관심 가져 주셔서 대단히 감사합니다.

살펴보니 krx에서 가져오는데, 홈페이지가 개편이 있었던 모양이네요.
수정하고 알려드리겠습니다.

이슈 생성해주셔서 대단히 감사합니다.

**Comment by mrchypark** [comment]
@all-contributors please add @gbkim01 for bugreport

**Comment by mrchypark** [comment]
@all-contributors please add @gbkim01 for bug

**Comment by mrchypark** [comment]
기능을 수정하였습니다. 데이터를 가져오는 페이지가 수정되어서, 모두 처음부터 가져오는 형태로 동작을 수정하였습니다.
시장을 선택해서 가져오는 것이 아니라, 전체를 가져오고 시장 정보가 함께 있습니다.

https://github.com/mrchypark/tqk/pull/28
