### ISSUE TITLE
ymd 의존성의 동작 버그

### ISSUE THREAD

**Issue by mrchypark** [mrchypark/tqk#37]
![image](https://user-images.githubusercontent.com/6179259/184619971-7ce710d5-63c1-4b97-8a54-31db0ad504f3.png)

**Comment by mrchypark** [comment]
ymd가 문제가 아니고, 응답 구조가 변경된 듯. 확인이 필요.

**Comment by mrchypark** [comment]
그러고 보니, 외부 서비스의 응답 검증 로직이 있으면 좋겠다.
여기서 문제가 되면, 다른 에러 메세지를 줄 수 있으니.

**Comment by mrchypark** [comment]
응답 구조 문제가 아니고, stock code를 받을 때 동작이 바뀌었음. 버전차이인가?

stock code 의 검증과정이 필요함.

**Comment by seohyunjun** [comment]
> 그러고 보니, 외부 서비스의 응답 검증 로직이 있으면 좋겠다.
> 
> 여기서 문제가 되면, 다른 에러 메세지를 줄 수 있으니.

Heroku+python+telegram 서버 상태 모니터링 하는 거 추천드립니다.

**Comment by mrchypark** [comment]
@seohyunjun 안녕하세요! 관심 가져주셔서 감사합니다. :)

제가 작업을 혼자하다보니 글을 좀 오해하기 좋게 부족한 정보로 작성한 것 같습니다.
작성한 `응답 검증 로직`은 응답의 형태나 데이터 존재 등을 검증하는 부분을 의미하였습니다.
동작하는지는 생각하지 못하고 있었는데, 댓글을 읽고 보니 그렇게 이해하실 수 있겠다 싶더라구요.

아시겠지만, 위에 인용하신 글은 제가 문제 진단을 잘못한 내용이며, 본 이슈의 문제점 자체는 잘 해결하였습니다.

모니터링도 도구가 다양하니 혹시 필요하니 일이 있을 때 제안 주신 구성을 참고해보겠습니다.

다시 한번 관심 가져주셔서 감사합니다. :)

**Comment by seohyunjun** [comment]
좋은 패키지 만들어 주셔서 감사합니다.
